"""add_offer_model

Revision ID: d95a6b70c51d
Revises: 
Create Date: 2026-05-15 17:26:45.822079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95a6b70c51d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.token_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_watch_id'), ['watch_id'], unique=False)

    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.drop_column('shipping_deadline')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_deadline', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_watch_id'))
        batch_op.drop_index(batch_op.f('ix_offers_id'))

    op.drop_table('offers')
    # ### end Alembic commands ###
